// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnVa52yS7IaeJ8RRCcFkBArDhSFh0eMss',
    appId: '1:882751944221:web:b9ed919061a59c21fe78f4',
    messagingSenderId: '882751944221',
    projectId: 'davidsworkdriveapp',
    authDomain: 'davidsworkdriveapp.firebaseapp.com',
    storageBucket: 'davidsworkdriveapp.appspot.com',
    measurementId: 'G-4S23NZ414S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5aNkNi3COQE3tY3L3cfZ7Re1rwqN2pnY',
    appId: '1:882751944221:android:dba4e27c1917c9b8fe78f4',
    messagingSenderId: '882751944221',
    projectId: 'davidsworkdriveapp',
    storageBucket: 'davidsworkdriveapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfO1ZpdNTo2OO1sgRgtZMol-yY5JQ5Gec',
    appId: '1:882751944221:ios:8f454639f46509f2fe78f4',
    messagingSenderId: '882751944221',
    projectId: 'davidsworkdriveapp',
    storageBucket: 'davidsworkdriveapp.appspot.com',
    iosBundleId: 'com.anipopplaza.funkyRoutes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfO1ZpdNTo2OO1sgRgtZMol-yY5JQ5Gec',
    appId: '1:882751944221:ios:9731cc043a65f191fe78f4',
    messagingSenderId: '882751944221',
    projectId: 'davidsworkdriveapp',
    storageBucket: 'davidsworkdriveapp.appspot.com',
    iosBundleId: 'com.anipopplaza.funkyRoutes.RunnerTests',
  );
}
